### ISSUE TITLE
Page renders nicely; follows spec

### ISSUE THREAD

**Issue by sdhunt** [WKenC/ColmarAcademy#1]
Great job on producing a page that follows the project specification!

The page responds well to browser size changes too.

I like your use of the `:hover` attribute for your "clickable" items. 
* A tip: add the `cursor: pointer;` attribute to those items, so that the mouse shows the "hand" icon when hovering over something that the user can click on. This is a standard convention that users are used to seeing.

**Comment by WKenC** [comment]
Thanks for the tip.
