### ISSUE TITLE
CSS is neat too

### ISSUE THREAD

**Issue by sdhunt** [WKenC/ColmarAcademy#4]
Your CSS code is also neat and "clean". 

A couple of things to do to make it adhere more to accepted standards: 
* use _all-lower-case-hyphen-delimited_ names for `id` and `class` attributes
* include a space before the opening `{` of the rule

https://github.com/WKenC/ColmarAcademy/blob/81a11908d8095c8273a0617ef31916c2e4c13fc1/resources/css/style.css#L114

The above should look more like:

      .banner-picture {

**Comment by WKenC** [comment]
Got it, thanks.
