### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by sdhunt** [WKenC/ColmarAcademy#5]
_Grade:_ __Meets Expectations__

In all, a pretty solid piece of work -- well done!

You should feel good about:
* HTML indentation neat and well organized
* Good use of `:hover` attribute for clickable items, with visual change
* Using semantic elements (`<header>` etc.)
* Good understanding and use of CSS classes for element styling

Some things to pay attention to:
* Use some whitespace (blank lines) and comments to break up your source code, so it isn't one solid block of text
* Remember to include an `alt` attribute on your `<img>` elements
* Use conventional naming format for `id` and `class` attributes
* Use `cursor: pointer;` for clickable items

You might find the following articles an interesting read:
* https://www.smashingmagazine.com/2008/11/12-principles-for-keeping-your-code-clean/
* https://learn.shayhowe.com/html-css/writing-your-best-code/

Keep up the good work -- you have definitely started to gain some good HTML coding habits!

**Comment by WKenC** [comment]
Thank for your time to review my work and also sharing the articles.
